spring:
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/devSpace
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect